services:
    nahoy_api_platform_plan.load_class_metadata_listener:
        class: Nahoy\ApiPlatform\PlanBundle\Doctrine\LoadClassMetadataListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber }